package com.nwpengdep.hrms.entity;

public enum RequirementType {
    EB_GRADE_3,
    EB_GRADE_2,
    GOVERNMENT_LANGUAGE_QUALIFICATION,
    MEDICAL_REPORT,
    OL_CERTIFICATE,
    AL_CERTIFICATE,
    DEGREE_CERTIFICATE,
    OTHER_CERTIFICATE,
    BIRTH_CERTIFICATE,
    OTHER_GRADE_2_REQUIREMENT,
    EB_GRADE_1,
    SUPRA_REQUIREMENT,
    SPECIAL_GRADE_REQUIREMENT,
    TRAINING_PROGRAM,
    PROFESSIONAL_QUALIFICATION,
    CUSTOM_PERMANENT_REQUIREMENT,
    CUSTOM_GRADE_2_REQUIREMENT,
    CUSTOM_GRADE_1_REQUIREMENT
}
