apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrms-uploads
  labels:
    app: hrms-backend
    purpose: uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
