ALTER TABLE employee_actions
MODIFY COLUMN action_type ENUM(
    'NEW_APPOINTMENT',
    'TRANSFER_IN',
    'TRANSFER_OUT',
    'PROMOTION',
    'ASSIGNMENT_GRADE_UPDATE',
    'PERMANENT_CONFIRMATION',
    'RETIREMENT_OR_RESIGNATION',
    'DEATH',
    'DISMISSAL'
) NOT NULL;
