CREATE TABLE IF NOT EXISTS audit_logs (
  id              BIGINT AUTO_INCREMENT PRIMARY KEY,
  occurred_at     DATETIME(3) NOT NULL,
  action          VARCHAR(32) NOT NULL,
  entity_type     VARCHAR(64),
  entity_id       VARCHAR(64),
  entity_label    VARCHAR(255),
  user_id         BIGINT,
  username        VARCHAR(100) NOT NULL,
  user_role       VARCHAR(32) NOT NULL,
  ip_address      VARCHAR(45),
  user_agent      VARCHAR(512),
  client_host     VARCHAR(255),
  http_method     VARCHAR(10),
  request_path    VARCHAR(512),
  correlation_id  VARCHAR(36),
  session_id      VARCHAR(64),
  status          VARCHAR(16) NOT NULL,
  failure_reason  VARCHAR(500),
  source_module   VARCHAR(64),
  export_format   VARCHAR(16),
  record_count    INT,
  is_sensitive    TINYINT(1) DEFAULT 0,
  activity_summary VARCHAR(255),
  changed_fields  JSON,
  old_values      JSON,
  new_values      JSON,
  content_hash    VARCHAR(64),
  INDEX idx_occurred_at (occurred_at),
  INDEX idx_username (username),
  INDEX idx_action (action),
  INDEX idx_entity (entity_type, entity_id),
  INDEX idx_ip (ip_address)
);
